[project]
name = "retailops-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sudhanshukhare18", email = "sudhanshukhare021@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=4.0.3",
    "psycopg[binary,pool]>=3.3.5",
    "python-dotenv>=1.2.3",
    "bcrypt"
]

[project.scripts]
retailops-mcp = "retailops_mcp:main"

[build-system]
requires = ["uv_build>=0.12.11,<0.13.0"]
build-backend = "uv_build"
